<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $brandSpecs = [
            'nordvpn' => [
                'servers' => '5,400+ máy chủ',
                'countries' => '60+ quốc gia',
                'devices' => '6 thiết bị',
                'speed' => 'Rất Nhanh',
                'protocol' => 'NordLynx (WireGuard)',
                'headquarter' => 'Panama',
                'refund' => '30 ngày',
                'founded' => '2012',
                'description' => 'NordVPN là một trong những dịch vụ VPN phổ biến nhất thế giới, nổi tiếng với tốc độ nhanh, bảo mật cao và giao diện thân thiện. Với hơn 5,400 máy chủ tại 60+ quốc gia, NordVPN đảm bảo kết nối ổn định và tốc độ tối ưu.',
            ],
            'expressvpn' => [
                'servers' => '3,000+ máy chủ',
                'countries' => '94+ quốc gia',
                'devices' => '5 thiết bị',
                'speed' => 'Siêu Nhanh',
                'protocol' => 'Lightway',
                'headquarter' => 'British Virgin Islands',
                'refund' => '30 ngày',
                'founded' => '2009',
                'description' => 'ExpressVPN là lựa chọn hàng đầu cho tốc độ và độ tin cậy. Giao thức Lightway độc quyền cho phép kết nối nhanh, ổn định và bảo mật cao. Hỗ trợ 94+ quốc gia với hơn 3,000 máy chủ tốc độ cao.',
            ],
            'surfshark' => [
                'servers' => '3,200+ máy chủ',
                'countries' => '100+ quốc gia',
                'devices' => 'Không giới hạn',
                'speed' => 'Nhanh',
                'protocol' => 'WireGuard / IKEv2',
                'headquarter' => 'Netherlands',
                'refund' => '30 ngày',
                'founded' => '2018',
                'description' => 'Surfshark nổi bật với chính sách cho phép kết nối không giới hạn thiết bị, lý tưởng cho gia đình. Tính năng CleanWeb chặn quảng cáo và malware, Camouflage Mode che giấu hoạt động VPN.',
            ],
            'hma' => [
                'servers' => '1,100+ máy chủ',
                'countries' => '190+ quốc gia',
                'devices' => '5 thiết bị',
                'speed' => 'Nhanh',
                'protocol' => 'OpenVPN / IKEv2',
                'headquarter' => 'United Kingdom',
                'refund' => '30 ngày',
                'founded' => '2005',
                'description' => 'HMA (Hide My Ass!) là một trong những VPN lâu đời nhất với mạng lưới máy chủ tại 190+ quốc gia, nhiều hơn hầu hết các đối thủ. Giao diện đơn giản, dễ sử dụng phù hợp với người mới bắt đầu.',
            ],
            'cyberghost' => [
                'servers' => '9,700+ máy chủ',
                'countries' => '91+ quốc gia',
                'devices' => '7 thiết bị',
                'speed' => 'Nhanh',
                'protocol' => 'WireGuard / OpenVPN',
                'headquarter' => 'Romania',
                'refund' => '45 ngày',
                'founded' => '2011',
                'description' => 'CyberGhost có mạng lưới máy chủ lớn nhất với 9,700+ server và chính sách hoàn tiền 45 ngày - dài nhất trong ngành. Máy chủ chuyên dụng cho streaming và torrenting được gắn nhãn rõ ràng.',
            ],
            'purevpn' => [
                'servers' => '6,500+ máy chủ',
                'countries' => '78+ quốc gia',
                'devices' => '10 thiết bị',
                'speed' => 'Nhanh',
                'protocol' => 'WireGuard / OpenVPN',
                'headquarter' => 'British Virgin Islands',
                'refund' => '31 ngày',
                'founded' => '2007',
                'description' => 'PureVPN cho phép kết nối đến 10 thiết bị đồng thời với hơn 6,500 máy chủ tại 78+ quốc gia. Đã vượt qua kiểm toán bảo mật độc lập xác nhận chính sách không lưu log.',
            ],
            'ipvanish' => [
                'servers' => '2,200+ máy chủ',
                'countries' => '75+ quốc gia',
                'devices' => 'Không giới hạn',
                'speed' => 'Nhanh',
                'protocol' => 'WireGuard / OpenVPN',
                'headquarter' => 'United States',
                'refund' => '30 ngày',
                'founded' => '2012',
                'description' => 'IPVanish là lựa chọn tuyệt vời cho người dùng cần không giới hạn thiết bị kết nối đồng thời. Hỗ trợ SOCKS5 proxy, lý tưởng cho torrent và P2P. Có ứng dụng native cho mọi nền tảng.',
            ],
            'protonvpn' => [
                'servers' => '3,000+ máy chủ',
                'countries' => '67+ quốc gia',
                'devices' => '10 thiết bị',
                'speed' => 'Nhanh',
                'protocol' => 'WireGuard / OpenVPN',
                'headquarter' => 'Switzerland',
                'refund' => '30 ngày',
                'founded' => '2017',
                'description' => 'ProtonVPN từ đội ngũ ProtonMail Thụy Sĩ - tập trung tuyệt đối vào quyền riêng tư. Tính năng Secure Core định tuyến lưu lượng qua nhiều máy chủ, cung cấp bảo vệ tốt nhất. Không bao giờ lưu log.',
            ],
        ];

        $products = [
            // NordVPN
            [
                'name' => 'NordVPN 1 Tháng',
                'brand' => 'NordVPN',
                'slug' => 'nordvpn',
                'color' => '#4687FF',
                'price' => 120000,
                'old_price' => 200000,
                'plan' => '1month',
                'rating' => 4.9,
                'reviews' => 1250,
                'features' => ['6 thiết bị', '5400+ máy chủ', 'Kill Switch', 'No-log'],
                'stock' => 999,
                'sold' => 142,
                'status' => 'active',
            ],
            [
                'name' => 'NordVPN 6 Tháng',
                'brand' => 'NordVPN',
                'slug' => 'nordvpn',
                'color' => '#4687FF',
                'price' => 350000,
                'old_price' => 700000,
                'plan' => '6month',
                'rating' => 4.9,
                'reviews' => 1250,
                'features' => ['6 thiết bị', '5400+ máy chủ', 'Kill Switch', 'No-log'],
                'stock' => 999,
                'sold' => 98,
                'status' => 'active',
            ],
            [
                'name' => 'NordVPN 1 Năm',
                'brand' => 'NordVPN',
                'slug' => 'nordvpn',
                'color' => '#4687FF',
                'price' => 599000,
                'old_price' => 1200000,
                'plan' => '1year',
                'rating' => 4.9,
                'reviews' => 1250,
                'features' => ['6 thiết bị', '5400+ máy chủ', 'Kill Switch', 'No-log'],
                'stock' => 999,
                'sold' => 285,
                'status' => 'active',
            ],
            [
                'name' => 'NordVPN 2 Năm',
                'brand' => 'NordVPN',
                'slug' => 'nordvpn',
                'color' => '#4687FF',
                'price' => 849000,
                'old_price' => 2400000,
                'plan' => '2year',
                'rating' => 4.9,
                'reviews' => 1250,
                'features' => ['6 thiết bị', '5400+ máy chủ', 'Kill Switch', 'No-log'],
                'stock' => 999,
                'sold' => 156,
                'status' => 'active',
            ],
            // ExpressVPN
            [
                'name' => 'ExpressVPN 1 Tháng',
                'brand' => 'ExpressVPN',
                'slug' => 'expressvpn',
                'color' => '#DA3940',
                'price' => 160000,
                'old_price' => 260000,
                'plan' => '1month',
                'rating' => 4.8,
                'reviews' => 980,
                'features' => ['5 thiết bị', '3000+ máy chủ', 'Lightway Protocol', '30 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 88,
                'status' => 'active',
            ],
            [
                'name' => 'ExpressVPN 6 Tháng',
                'brand' => 'ExpressVPN',
                'slug' => 'expressvpn',
                'color' => '#DA3940',
                'price' => 450000,
                'old_price' => 850000,
                'plan' => '6month',
                'rating' => 4.8,
                'reviews' => 980,
                'features' => ['5 thiết bị', '3000+ máy chủ', 'Lightway Protocol', '30 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 45,
                'status' => 'active',
            ],
            [
                'name' => 'ExpressVPN 1 Năm',
                'brand' => 'ExpressVPN',
                'slug' => 'expressvpn',
                'color' => '#DA3940',
                'price' => 799000,
                'old_price' => 1500000,
                'plan' => '1year',
                'rating' => 4.8,
                'reviews' => 980,
                'features' => ['5 thiết bị', '3000+ máy chủ', 'Lightway Protocol', '30 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 198,
                'status' => 'active',
            ],
            [
                'name' => 'ExpressVPN 2 Năm',
                'brand' => 'ExpressVPN',
                'slug' => 'expressvpn',
                'color' => '#DA3940',
                'price' => 1099000,
                'old_price' => 2800000,
                'plan' => '2year',
                'rating' => 4.8,
                'reviews' => 980,
                'features' => ['5 thiết bị', '3000+ máy chủ', 'Lightway Protocol', '30 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 56,
                'status' => 'active',
            ],
            // Surfshark
            [
                'name' => 'Surfshark 1 Tháng',
                'brand' => 'Surfshark',
                'slug' => 'surfshark',
                'color' => '#10B981',
                'price' => 89000,
                'old_price' => 180000,
                'plan' => '1month',
                'rating' => 4.8,
                'reviews' => 850,
                'features' => ['Không giới hạn thiết bị', '3200+ máy chủ', 'CleanWeb', 'Cam kết no-log'],
                'stock' => 999,
                'sold' => 34,
                'status' => 'active',
            ],
            [
                'name' => 'Surfshark 6 Tháng',
                'brand' => 'Surfshark',
                'slug' => 'surfshark',
                'color' => '#10B981',
                'price' => 279000,
                'old_price' => 600000,
                'plan' => '6month',
                'rating' => 4.8,
                'reviews' => 850,
                'features' => ['Không giới hạn thiết bị', '3200+ máy chủ', 'CleanWeb', 'Cam kết no-log'],
                'stock' => 999,
                'sold' => 15,
                'status' => 'active',
            ],
            [
                'name' => 'Surfshark 1 Năm',
                'brand' => 'Surfshark',
                'slug' => 'surfshark',
                'color' => '#10B981',
                'price' => 449000,
                'old_price' => 1100000,
                'plan' => '1year',
                'rating' => 4.8,
                'reviews' => 850,
                'features' => ['Không giới hạn thiết bị', '3200+ máy chủ', 'CleanWeb', 'Cam kết no-log'],
                'stock' => 999,
                'sold' => 241,
                'status' => 'active',
            ],
            [
                'name' => 'Surfshark 2 Năm',
                'brand' => 'Surfshark',
                'slug' => 'surfshark',
                'color' => '#10B981',
                'price' => 699000,
                'old_price' => 1800000,
                'plan' => '2year',
                'rating' => 4.8,
                'reviews' => 850,
                'features' => ['Không giới hạn thiết bị', '3200+ máy chủ', 'CleanWeb', 'Cam kết no-log'],
                'stock' => 999,
                'sold' => 167,
                'status' => 'active',
            ],
            // HMA
            [
                'name' => 'HMA VPN 1 Tháng',
                'brand' => 'HMA VPN',
                'slug' => 'hma',
                'color' => '#F59E0B',
                'price' => 79000,
                'old_price' => 150000,
                'plan' => '1month',
                'rating' => 4.6,
                'reviews' => 540,
                'features' => ['5 thiết bị', '290+ vị trí', 'Tốc độ cao', 'Hỗ trợ P2P'],
                'stock' => 999,
                'sold' => 14,
                'status' => 'active',
            ],
            [
                'name' => 'HMA VPN 1 Năm',
                'brand' => 'HMA VPN',
                'slug' => 'hma',
                'color' => '#F59E0B',
                'price' => 449000,
                'old_price' => 900000,
                'plan' => '1year',
                'rating' => 4.6,
                'reviews' => 540,
                'features' => ['5 thiết bị', '290+ vị trí', 'Tốc độ cao', 'Hỗ trợ P2P'],
                'stock' => 999,
                'sold' => 124,
                'status' => 'active',
            ],
            [
                'name' => 'HMA VPN 3 Năm',
                'brand' => 'HMA VPN',
                'slug' => 'hma',
                'color' => '#F59E0B',
                'price' => 799000,
                'old_price' => 2700000,
                'plan' => '3year',
                'rating' => 4.6,
                'reviews' => 540,
                'features' => ['5 thiết bị', '290+ vị trí', 'Tốc độ cao', 'Hỗ trợ P2P'],
                'stock' => 999,
                'sold' => 56,
                'status' => 'active',
            ],
            // CyberGhost
            [
                'name' => 'CyberGhost 1 Tháng',
                'brand' => 'CyberGhost',
                'slug' => 'cyberghost',
                'color' => '#8B5CF6',
                'price' => 99000,
                'old_price' => 190000,
                'plan' => '1month',
                'rating' => 4.7,
                'reviews' => 720,
                'features' => ['7 thiết bị', '9700+ máy chủ', 'Streaming server', '45 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 32,
                'status' => 'active',
            ],
            [
                'name' => 'CyberGhost 1 Năm',
                'brand' => 'CyberGhost',
                'slug' => 'cyberghost',
                'color' => '#8B5CF6',
                'price' => 299000,
                'old_price' => 700000,
                'plan' => '1year',
                'rating' => 4.7,
                'reviews' => 720,
                'features' => ['7 thiết bị', '9700+ máy chủ', 'Streaming server', '45 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 42,
                'status' => 'active',
            ],
            [
                'name' => 'CyberGhost 2 Năm',
                'brand' => 'CyberGhost',
                'slug' => 'cyberghost',
                'color' => '#8B5CF6',
                'price' => 399000,
                'old_price' => 1100000,
                'plan' => '2year',
                'rating' => 4.7,
                'reviews' => 720,
                'features' => ['7 thiết bị', '9700+ máy chủ', 'Streaming server', '45 ngày hoàn tiền'],
                'stock' => 999,
                'sold' => 156,
                'status' => 'active',
            ],
            // PureVPN
            [
                'name' => 'PureVPN 1 Năm',
                'brand' => 'PureVPN',
                'slug' => 'purevpn',
                'color' => '#EF4444',
                'price' => 249000,
                'old_price' => 600000,
                'plan' => '1year',
                'rating' => 4.5,
                'reviews' => 320,
                'features' => ['10 thiết bị', '6500+ máy chủ', 'Split Tunneling', 'No-log kiểm toán'],
                'stock' => 999,
                'sold' => 89,
                'status' => 'active',
            ],
            [
                'name' => 'PureVPN 2 Năm',
                'brand' => 'PureVPN',
                'slug' => 'purevpn',
                'color' => '#EF4444',
                'price' => 349000,
                'old_price' => 1200000,
                'plan' => '2year',
                'rating' => 4.5,
                'reviews' => 320,
                'features' => ['10 thiết bị', '6500+ máy chủ', 'Split Tunneling', 'No-log kiểm toán'],
                'stock' => 999,
                'sold' => 45,
                'status' => 'active',
            ],
            // IPVanish
            [
                'name' => 'IPVanish 1 Năm',
                'brand' => 'IPVanish',
                'slug' => 'ipvanish',
                'color' => '#0EA5E9',
                'price' => 399000,
                'old_price' => 900000,
                'plan' => '1year',
                'rating' => 4.7,
                'reviews' => 150,
                'features' => ['Không giới hạn thiết bị', '2000+ máy chủ', 'WireGuard Protocol', 'No-logs'],
                'stock' => 999,
                'sold' => 42,
                'status' => 'active',
            ],
            // ProtonVPN
            [
                'name' => 'ProtonVPN 1 Năm',
                'brand' => 'ProtonVPN',
                'slug' => 'protonvpn',
                'color' => '#6D28D9',
                'price' => 549000,
                'old_price' => 1000000,
                'plan' => '1year',
                'rating' => 4.8,
                'reviews' => 240,
                'features' => ['10 thiết bị', '2900+ máy chủ', 'NetShield AdBlock', 'High-speed code'],
                'stock' => 999,
                'sold' => 88,
                'status' => 'active',
            ],
        ];

        foreach ($products as $p) {
            $brandKey = $p['slug'];
            $specs = $brandSpecs[$brandKey] ?? [];
            $merged = array_merge($p, $specs);
            Product::updateOrCreate(
                ['name' => $p['name']],
                $merged
            );
        }
    }
}
